apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podexp
  name: podexp
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 10
    image: busybox
    name: podexp
    resources: {}
  - image: nginx
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
