apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
spec:
  capacity:
    storage: 10Ki
  volumeMode: Filesystem # Filesystem, Block
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle # Retain, Recycle, Delete # Recycle means recycles when PV is given to a new claim, not a new pod VVI!
  # storageClassName: slow
  hostPath: 
    path: /pv01