apiVersion: v1
kind: Pod
metadata:
  name: nginx-in-dev-ns
  labels:
    app: nginx-in-dev-ns
  namespace: dev
spec:
  containers:
    - name: nginx-in-dev-ns
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
