kind: Pod
apiVersion: v1
metadata:
  name: my-first-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-app
      image: nginx
      resources:
        limits:
          cpu: 128m
          memory: 128Mi
      ports:
        - containerPort: 80