apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpathvol
  name: hostpathvol
spec:
  containers:
  - image: nginx
    name: hostpathvol
    resources: {}
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: test-volume
    hostPath:
      path: /my/hostpath/exp/ab8c0
      type: DirectoryOrCreate
status: {}