apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: dev
  name: d-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
  name: d-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - image: nginx
        name: nginx