apiVersion: v1
kind: Pod
metadata:
  labels:
    run: task34
  name: task34
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo [$(date)] Hi I am from Main container >> /var/log/index.html; sleep 5; done
    image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /var/log
      name: task34vol
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: task34vol
  restartPolicy: Never
  
  volumes:
  - name: task34vol
    emptyDir: {}
