apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secctx
  name: secctx
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: secctx

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  
