apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cmpod
  name: cmpod
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: cmpod
    envFrom:
      - configMapRef:
          name: cmfile

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  
