apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret
  name: secret
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: secret
    envFrom:
    - secretRef:
        name: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
