apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-job
spec:
  jobTemplate:
    metadata:
      name: date-job
    spec:
      # completions: 5 # every trigger(every minute) runs 5 jobs 2 in parallel!
      # parallelism: 2 
      template:
        metadata:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date;echo hello from k8s cluster
            image: busybox
            name: date-job
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
