apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-nginx
  name: my-nginx
spec:
  containers:
  - image: nginx
    name: my-nginx
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-nginx
spec:
  # type: NodePort
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376 # for some reason its not working in minikube, just port works fine.
      # nodePort: 30001