apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: "manual" 
  # volumeName: myVolume # does not work!
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

--- 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
        name: http-port
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: data
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: task-pv-claim
