apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:14.5
    ports:
    - containerPort: 5432
    readinessProbe:
      tcpSocket: 
        port: 5432
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 5
    env:
      - name: POSTGRES_PASSWORD
        value: postgres123
      - name: POSTGRES_USER
        value: pguser
