apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb1
  name: bb1
spec:
  containers:
  - args:
    - env
    image: busybox
    name: bb1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
