apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp
  name: tmp
spec:
  containers:
  - args:
    - wget
    - -O-
    - http://10.244.1.6/
    image: busybox
    name: tmp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
