apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: rq-demo
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "250m"
        cpu: "500m"
      limits:
        memory: "500m"
        cpu: "1000m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
