apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-team
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-team-secret
  annotations:
    kubernetes.io/service-account.name: backend-team
type: kubernetes.io/service-account-token
--- 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  # serviceAccount: backend-team
  serviceAccountName: backend-team # go with this as it's in the documentation.
  automountServiceAccountToken: true
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
