apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb1
  name: bb1
spec:
  containers:
  - args:
    - sh
    - -c
    - echo hello container 01 > echo.txt; sleep 3600
    image: busybox
    name: bb1c1
    resources: {}
  - args:
    - sh
    - -c
    - echo hello container 02 > echo.txt; sleep 3600
    image: busybox
    name: bb1c2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
