apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: sharedvol
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'wget -O /work-dir/index.html http://neverssl.com/online']
    volumeMounts:
    - mountPath: /work-dir/
      name: sharedvol
  volumes:
  - name: sharedvol
    emptyDir: {}
status: {}
