apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: c1
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: sharedvol
  - args:
    - sleep
    - "3600"
    image: busybox
    name: c2
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: sharedvol
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: sharedvol
      emptyDir: {}
status: {}
