apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox2
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox2
    resources: {}
    volumeMounts:
        - mountPath: "/etc/foo"
          name: task-pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
