apiVersion: v1
kind: Pod
metadata:
  name: bb5
spec:
  containers:
    - name: bb5
      image: busybox
      command: [ "/bin/sh", "-c", "sleep 300" ]
      volumeMounts:
      - name: foo
        mountPath: /etc/config
        readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: db-access
  restartPolicy: Never