apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
