apiVersion: v1
kind: ConfigMap
metadata:
  name: course03-practice-cm
data:
  DB_URL: jdbc:postgresql://192.168.0.100:5432/postgres
  DB_USERNAME: postgres
  DB_POOL_SIZE: "5"
  PING_LOG: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: course03-practice-secret
data:
  DB_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Pod
metadata:
  name: course03-practice-pod
spec:
  containers:
    - name: healthy-sec-cm-prac
      image: ivplay4689/healthy:12a933
      ports:
        - containerPort: 80
          name: healthy-port
      startupProbe: # 2 min timeout
        httpGet:
          path: /
          port: 80
        failureThreshold: 24
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /live
          port: 80
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 80
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
        periodSeconds: 10
      envFrom:
      - secretRef:
          name: course03-practice-secret
      - configMapRef:
          name: course03-practice-cm
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: course03-debug-pod
spec:
  containers:
    - name: healthy-sec-cm-prac
      image: ubuntu
      command: ["sh","-c"]
      args: 
        - echo $(pwd);
          echo $DB_URL;
          echo $DB_USERNAME;
          echo $DB_PASSWORD;
          echo $DB_POOL_SIZE;
          echo $PING_LOG;
          echo $MY_POD_NAME;
          echo $MY_POD_NAMESPACE;
          echo $MY_POD_IP;
      envFrom:
      - secretRef:
          name: course03-practice-secret
      - configMapRef:
          name: course03-practice-cm
  restartPolicy: Never
