apiVersion: v1
kind: Namespace
metadata:
  name: resource-quota-ns
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox-rq
  name: busybox-rq
  namespace: resource-quota-ns
spec:
  containers:
    - image: busybox:stable
      name: busybox
      resources:
        requests:
          cpu: 250m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
      command: ['sh','-c','while true; do echo Running...; sleep 5; done']
  restartPolicy: Always
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-test
  namespace: resource-quota-ns
spec:
  hard:
    pods: "2"
    requests.memory: 128Mi
    requests.cpu: 500m
    limits.memory: 256Mi
    limits.cpu: "1"

