apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: mysecret-course03
type: Opaque
--- 
apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret-course03
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: mysecret
      mountPath: "/etc/mysecret"
      readOnly: true
  volumes:
  - name: mysecret
    secret:
      secretName: mysecret-course03
      optional: false 