apiVersion: v1
kind: Pod
metadata:
  name: "sec-ctx"
spec:
  containers:
  - name: nginx
    image: "nginx"
    # command: ['sh','-c','while true; do echo Running...; sleep 5; done']
    securityContext:
      # capabilities:
      #   add: ["NET_ADMIN", "SYS_TIME"]
      # runAsUser: 3000
      # runAsGroup: 4000
      # allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    ports:
      - containerPort: 80

    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  restartPolicy: Never