apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity: 
    storage: 100Ki
  accessModes:
    - ReadWriteOnce
  storageClassName: najimsstorageclass # can be anythin I want!!!
  hostPath:
    path: /my-pv-dir
    type: DirectoryOrCreate
    
