apiVersion: batch/v1
kind: Job
metadata:
  name: self-job
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/sh","-c"]
        args:
          - ls -la;
            echo 'Hello World';
      restartPolicy: Never
  backoffLimit: 4
