apiVersion: v1
kind: Pod
metadata:
  name: vol-test-01
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sh","-c","ls -la; cat /vol-path/testfile.txt;"]
    volumeMounts:
      - name: my-vol-01
        mountPath: /vol-path
  volumes:
    - name: my-vol-01
      hostPath:
        path: /testdir
        type: Directory

