apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxnm
  name: nginxnm
spec:
  containers:
  - image: nginx
    name: nginxnm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    accelerator: nvidia-tesla-p100
status: {}
