apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-aff
  namespace: default
  labels:
    app:  nginx-aff
spec:
  selector:
    matchLabels:
      app: nginx-aff
  replicas: 3
  template:
    metadata:
      labels:
        app:  nginx-aff
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - large
      containers:
      - name:  nginx-aff
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        
        ports:
        - containerPort:  80
          name:  nginx-aff
        
      restartPolicy: Always