apiVersion: v1
kind: Pod
metadata:
  name: "ubuntu-sec-ctx"
  namespace: default
  labels:
    app: "ubuntu-sec-ctx"
spec:
  securityContext:
    runAsUser: 1000 # verified
  containers:
  - name: ubuntu-sec-ctx
    image: "ubuntu:latest"
    command: ["sleep"]
    args: ["300"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: OnFailure