# mount with custom service account

apiVersion: v1
kind: Pod
metadata:
  name: "nginx-service-account-01"
  namespace: default
  labels:
    app: "nginx"
spec:    
  serviceAccountName: my-first-service-account # adding service account ?? does not work
  # serviceAccount: my-first-service-account # adding service account ?? does not work
  # automountServiceAccountToken: true
  containers:
  - name: nginx
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always