# mount with custom service account

apiVersion: v1
kind: Pod
metadata:
  name: "nginx-service-account-02"
  namespace: default
  labels:
    app: "nginx"
spec:
  automountServiceAccountToken: false # works
  containers:
  - name: nginx
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always