apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: bash
    command: ['sh','-c','sleep 1d']
    envFrom:
      - configMapRef:
          name: drinks
    volumeMounts:
    - name: foo
      mountPath: "/tmp/secret1"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: secret1
