apiVersion: v1
kind: Pod
metadata:
  labels:
    my-label: test
  name: bash
spec:
  containers:
  - image: bash
    name: bash
    command: ["sh","-c","hostname > /tmp/hostname && sleep 1d"]
    volumeMounts:
      - name: a-volume
        mountPath: /tmp
  volumes:
    - name: a-volume
      emptyDir: {}
