apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dnginx
  name: dnginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnginx
  template:
    metadata:
      labels:
        app: dnginx
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        ports:
        - containerPort: 80
