apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ngcm
  name: ngcm
spec:
  containers:
  - image: nginx
    name: ngcm
    env:
        - name: option
          valueFrom:
            configMapKeyRef:
              name: options
              key: var5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
