apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    volumeMounts:
    - mountPath: /work-dir
      name: shared
    command: ['sh', '-c', "wget -O /work-dir/index.html http://neverssl.com/online"]
