apiVersion: v1
kind: Pod
metadata:
  name: "healthy-again"
  namespace: default
  labels:
    app: "healthy-again"
    service: "common-service"
spec:
  containers:
  - name: healthy-again
    image: "ivplay4689/healthy:9ee6a3"
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 200Mi
    env:
      - name: SERVER_PORT
        value: "8080"
      - name: DB_URL
        value: jdbc:postgresql://192.168.0.100:5432/k8sdb
      - name: DB_USERNAME
        value: postgres 
      - name: DB_PASSWORD
        value: postgres
      - name: DB_POOL_SIZE
        value: "5"
      - name: PING_LOG
        value: "1"
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
        - containerPort:  80
          name:  healthy
  restartPolicy: Always