apiVersion: v1
kind: Pod
metadata:
  name: bb4
spec:
  containers:
    - name: bb4
      image: busybox
      command: [ "/bin/sh", "-c", "sleep 300" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: cmff
  restartPolicy: Never