apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ng1
  name: ng1
spec:
  containers:
  - image: nginx
    name: ng1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "ec2"
    operator: "Equal"
    value: "m4large"  # Allow this pod to go to ec2=m4large, however it's not gurranted , effectively what I am telling here is `I don't mind if the pod goes to ec2=m4large`
    effect: "NoExecute"
  - key: "hdd" # Effectively what I am telling here is `I don't mind if the pod goes to an instance that is running on hdd`
    operator: "Exists" 
    effect: "NoExecute"
